f1=open("file1.txt","w")
f1.write("jashobanta sasmal \n")
f1.write("python file")
f1.close()
f1=open("file1.txt","r")
f2=open("file2.txt","w")
data=f1.read()
f2.write(data)
print("content copied succesfully")
